### PR TITLE
Replace string concatenation as argument StringBuffer.append() with chained append() calls

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by SlavaRa** [comment]
https://issues.apache.org/jira/browse/FLEX-34946

**Comment by tomchiverton** [comment]
I don't see any reasoning behind why this was done - is this approach more performant or something ?

**Comment by SlavaRa** [comment]
I would like to help in the development of the compiler.
But there is no desire to work with code that looks bad to say the least.
Using string concatenation contradicts the sense of using StringBuffer.
And yes, this has a negative impact on performance.

**Comment by Harbs** [comment]
I'd think the compiler optimizes the string concatenation, so there's no difference in performance:
http://stackoverflow.com/questions/1532461/stringbuilder-vs-string-concatenation-in-tostring-in-java

Is that not the case?

I think "looks bad" is a personal preference. Simple string concatenation is definitely more legible.

**Comment by SlavaRa** [comment]
"I think "looks bad" is a personal preference."
Perhaps, but in this situation, combined the two approaches StringBuffer.append and string concatenations.. in this case, the compiler can not generate correct optimization.

**Comment by aharui** [comment]
Hi SlavaRa,

(Apologies if this gets posted twice.  I think email replies as comments isn't working)

Do you have a link that supports your claim that the compiler cannot
generate the correct optimization?  This article seems to imply that it
can [1]

IMO, the string concatenation is easier to read.  I would want to see
actual profiling that shows that the string concatenation is affecting
compile times in a significant way.

But the most important question to me is:  Is there a reason you want to
work on the mxmlc compiler?  The “falcon” compiler in the flex-falcon repo
is under much more active development and it would be lower risk to be
doing optimizations in that code base.  The “falcon” compiler is the
compiler for the new FlexJS framework and I believe there is still a
reasonable chance it could replace the mxmlc compiler in Flex SDKs some
day.

-Alex

[1]
http://stackoverflow.com/questions/1532461/stringbuilder-vs-string-concatenation-in-tostring-in-java

**Pull request closed without merging**
