### PR TITLE
Fix FLEX-15159 by making ArrayList extend Proxy.

### PR DESCRIPTION
**Pull request by Dretch**
This fixes https://issues.apache.org/jira/browse/FLEX-15159.

Notes:
- This is more-or-less a copy-paste job with code taken from `ListCollectionView`
- I have patched both `mx.collections.ArrayList` and also `org.apache.flex.collections.ArrayList`
- I have written a unit test for the changes and put it in what seems to be a logical place. The test passes, but can't figure out how to get the build to call it. I was having segfault problems with my flashplayer that made it difficult to look into this further. It is possible (and I hope it is the case) that something in the build will call this test.

### CODE REVIEW

**Comment by Dretch** [comment]
I have moved the test to the framework project, where it is now called by the build. I have also added a warning to the documentation about how slow array access notation can be (I also had to rebase).

Please could Flex consider merging this pull request?

**Comment by Dretch** [comment]
Bump. Could this pull request be considered?

**Comment by roberthunt** [comment]
I would appreciate this being merged.

**Comment by tomforster** [comment]
+1 this would be nice to have and a clear improvement to a common use case.

**Comment by Harbs** [comment]
Using Proxy as a base class for ArrayList will likely have a significant performance hit. It seems questionable as to whether the benefits of using for each loops outweigh the performance hit.
http://blogs.adobe.com/aharui/2007/10/actionscript_readwrite_perform_1.html

It might be a good idea to get some performance metrics on ArrayList with and without Proxy.

Another approach might be to instead of modifying ArrayList itself to be a subclass of Proxy, to create a new IList to complement it with these changes. That way clients can decide whether they care about performance of for each loops.

**Comment by Dretch** [comment]
I don't care about this any more, and I don't think anyone else does either!

**Pull request closed without merging**
